export interface Country {
  code: string;
  name: string;
  dialCode: string;
  flag: string;
  regex: RegExp;
}

export const countries: Country[] = [
  { code: 'US', name: 'United States', dialCode: '+1', flag: '🇺🇸', regex: /^[2-9]\d{9}$/ },
  { code: 'GB', name: 'United Kingdom', dialCode: '+44', flag: '🇬🇧', regex: /^(7\d{9}|1\d{9,10}|2\d{9,10})$/ },
  { code: 'IN', name: 'India', dialCode: '+91', flag: '🇮🇳', regex: /^[6-9]\d{9}$/ },
  { code: 'CA', name: 'Canada', dialCode: '+1', flag: '🇨🇦', regex: /^[2-9]\d{9}$/ },
  { code: 'AU', name: 'Australia', dialCode: '+61', flag: '🇦🇺', regex: /^4\d{8}$/ },
  { code: 'DE', name: 'Germany', dialCode: '+49', flag: '🇩🇪', regex: /^([1-9]\d{3,11})$/ },
  { code: 'FR', name: 'France', dialCode: '+33', flag: '🇫🇷', regex: /^[1-9]\d{8}$/ },
  { code: 'IT', name: 'Italy', dialCode: '+39', flag: '🇮🇹', regex: /^[3-9]\d{8,10}$/ },
  { code: 'ES', name: 'Spain', dialCode: '+34', flag: '🇪🇸', regex: /^[6-9]\d{8}$/ },
  { code: 'BR', name: 'Brazil', dialCode: '+55', flag: '🇧🇷', regex: /^[1-9]\d{9,10}$/ },
  { code: 'MX', name: 'Mexico', dialCode: '+52', flag: '🇲🇽', regex: /^[1-9]\d{9,10}$/ },
  { code: 'AR', name: 'Argentina', dialCode: '+54', flag: '🇦🇷', regex: /^([1-9]\d{9,10})$/ },
  { code: 'CN', name: 'China', dialCode: '+86', flag: '🇨🇳', regex: /^1[3-9]\d{9}$/ },
  { code: 'JP', name: 'Japan', dialCode: '+81', flag: '🇯🇵', regex: /^0\d{9,10}$/ },
  { code: 'KR', name: 'South Korea', dialCode: '+82', flag: '🇰🇷', regex: /^(1[0-9]{9}|[2-9][0-9]{7,8})$/ },
  { code: 'SG', name: 'Singapore', dialCode: '+65', flag: '🇸🇬', regex: /^[689]\d{7}$/ },
  { code: 'AE', name: 'UAE', dialCode: '+971', flag: '🇦🇪', regex: /^5\d{8}$/ },
  { code: 'SA', name: 'Saudi Arabia', dialCode: '+966', flag: '🇸🇦', regex: /^5\d{8}$/ },
  { code: 'ZA', name: 'South Africa', dialCode: '+27', flag: '🇿🇦', regex: /^0\d{9}$/ },
  { code: 'NG', name: 'Nigeria', dialCode: '+234', flag: '🇳🇬', regex: /^0\d{10}$/ },
  { code: 'KE', name: 'Kenya', dialCode: '+254', flag: '🇰🇪', regex: /^0\d{9}$/ },
  { code: 'EG', name: 'Egypt', dialCode: '+20', flag: '🇪🇬', regex: /^1\d{9}$/ },
  { code: 'RU', name: 'Russia', dialCode: '+7', flag: '🇷🇺', regex: /^9\d{9}$/ },
  { code: 'TR', name: 'Turkey', dialCode: '+90', flag: '🇹🇷', regex: /^5\d{9}$/ },
  { code: 'PL', name: 'Poland', dialCode: '+48', flag: '🇵🇱', regex: /^[1-9]\d{8}$/ },
  { code: 'NL', name: 'Netherlands', dialCode: '+31', flag: '🇳🇱', regex: /^6\d{8}$/ },
  { code: 'BE', name: 'Belgium', dialCode: '+32', flag: '🇧🇪', regex: /^4\d{8}$/ },
  { code: 'SE', name: 'Sweden', dialCode: '+46', flag: '🇸🇪', regex: /^([1-9]\d{8,9})$/ },
  { code: 'NO', name: 'Norway', dialCode: '+47', flag: '🇳🇴', regex: /^\d{8}$/ },
  { code: 'DK', name: 'Denmark', dialCode: '+45', flag: '🇩🇰', regex: /^\d{8}$/ },
  { code: 'FI', name: 'Finland', dialCode: '+358', flag: '🇫🇮', regex: /^4\d{8,9}$/ },
  { code: 'CH', name: 'Switzerland', dialCode: '+41', flag: '🇨🇭', regex: /^7\d{8}$/ },
  { code: 'AT', name: 'Austria', dialCode: '+43', flag: '🇦🇹', regex: /^6\d{8,9}$/ },
  { code: 'PT', name: 'Portugal', dialCode: '+351', flag: '🇵🇹', regex: /^9\d{8}$/ },
  { code: 'GR', name: 'Greece', dialCode: '+30', flag: '🇬🇷', regex: /^6\d{9}$/ },
  { code: 'IL', name: 'Israel', dialCode: '+972', flag: '🇮🇱', regex: /^5\d{8}$/ },
  { code: 'TH', name: 'Thailand', dialCode: '+66', flag: '🇹🇭', regex: /^0\d{8,9}$/ },
  { code: 'MY', name: 'Malaysia', dialCode: '+60', flag: '🇲🇾', regex: /^1\d{8,9}$/ },
  { code: 'ID', name: 'Indonesia', dialCode: '+62', flag: '🇮🇩', regex: /^8\d{8,11}$/ },
  { code: 'PH', name: 'Philippines', dialCode: '+63', flag: '🇵🇭', regex: /^9\d{9}$/ },
  { code: 'VN', name: 'Vietnam', dialCode: '+84', flag: '🇻🇳', regex: /^0\d{9,10}$/ },
  { code: 'PK', name: 'Pakistan', dialCode: '+92', flag: '🇵🇰', regex: /^3\d{9}$/ },
  { code: 'BD', name: 'Bangladesh', dialCode: '+880', flag: '🇧🇩', regex: /^1\d{9}$/ },
  { code: 'NZ', name: 'New Zealand', dialCode: '+64', flag: '🇳🇿', regex: /^2\d{7,9}$/ },
  { code: 'IE', name: 'Ireland', dialCode: '+353', flag: '🇮🇪', regex: /^8\d{8}$/ },
];
