export interface Country {
  code: string;
  name: string;
  dialCode: string;
  flag: string;
  regex: RegExp;
}

export const countries: Country[] = [
  { code: 'US', name: 'United States', dialCode: '+1',   flag: 'US', regex: /^\d{10}$/ },                    
  { code: 'GB', name: 'United Kingdom', dialCode: '+44', flag: 'GB', regex: /^(\d{10}|7\d{9})$/ },          
  { code: 'IN', name: 'India',          dialCode: '+91', flag: 'IN', regex: /^\d{10}$/ },                     
  { code: 'CA', name: 'Canada',         dialCode: '+1',  flag: 'CA', regex: /^\d{10}$/ },                     
  { code: 'AU', name: 'Australia',      dialCode: '+61', flag: 'AU', regex: /^\d{9}$/ },                     
  { code: 'DE', name: 'Germany',        dialCode: '+49', flag: 'DE', regex: /^\d{10,11}$/ },                 
  { code: 'FR', name: 'France',         dialCode: '+33', flag: 'FR', regex: /^0\d{9}$/ },                  
  { code: 'IT', name: 'Italy',          dialCode: '+39', flag: 'IT', regex: /^\d{9,10}$/ },                 
  { code: 'ES', name: 'Spain',          dialCode: '+34', flag: 'ES', regex: /^\d{9}$/ },                  
  { code: 'BR', name: 'Brazil',         dialCode: '+55', flag: 'BR', regex: /^\d{11}$/ },                  
  { code: 'MX', name: 'Mexico',         dialCode: '+52', flag: 'MX', regex: /^\d{10}$/ },                  
  { code: 'AR', name: 'Argentina',      dialCode: '+54', flag: 'AR', regex: /^\d{10}$/ },                  
  { code: 'CN', name: 'China',          dialCode: '+86', flag: 'CN', regex: /^\d{11}$/ },                  
  { code: 'JP', name: 'Japan',          dialCode: '+81', flag: 'JP', regex: /^\d{10}$/ },                  
  { code: 'KR', name: 'South Korea',    dialCode: '+82', flag: 'KR', regex: /^\d{9,10}$/ },                
  { code: 'SG', name: 'Singapore',      dialCode: '+65', flag: 'SG', regex: /^\d{8}$/ },                   
  { code: 'AE', name: 'UAE',            dialCode: '+971',flag: 'AE', regex: /^\d{9}$/ },                  
  { code: 'SA', name: 'Saudi Arabia',   dialCode: '+966',flag: 'SA', regex: /^\d{9}$/ },                  
  { code: 'ZA', name: 'South Africa',   dialCode: '+27', flag: 'ZA', regex: /^\d{9}$/ },                  
  { code: 'NG', name: 'Nigeria',        dialCode: '+234',flag: 'NG', regex: /^\d{10}$/ },                 
  { code: 'KE', name: 'Kenya',          dialCode: '+254',flag: 'KE', regex: /^\d{9}$/ },                   
  { code: 'EG', name: 'Egypt',          dialCode: '+20', flag: 'EG', regex: /^\d{10}$/ },                  
  { code: 'RU', name: 'Russia',         dialCode: '+7',  flag: 'RU', regex: /^\d{10}$/ },                  
  { code: 'TR', name: 'Turkey',         dialCode: '+90', flag: 'TR', regex: /^\d{10}$/ },                 
  { code: 'PL', name: 'Poland',         dialCode: '+48', flag: 'PL', regex: /^\d{9}$/ },                   
  { code: 'NL', name: 'Netherlands',    dialCode: '+31', flag: 'NL', regex: /^\d{9}$/ },                   
  { code: 'BE', name: 'Belgium',        dialCode: '+32', flag: 'BE', regex: /^\d{9}$/ },                   
  { code: 'SE', name: 'Sweden',         dialCode: '+46', flag: 'SE', regex: /^\d{9,10}$/ },                
  { code: 'NO', name: 'Norway',         dialCode: '+47', flag: 'NO', regex: /^\d{8}$/ },                   
  { code: 'DK', name: 'Denmark',        dialCode: '+45', flag: 'DK', regex: /^\d{8}$/ },                   
  { code: 'FI', name: 'Finland',        dialCode: '+358',flag: 'FI', regex: /^\d{7,10}$/ },                
  { code: 'CH', name: 'Switzerland',    dialCode: '+41', flag: 'CH', regex: /^\d{9}$/ },                   
  { code: 'AT', name: 'Austria',        dialCode: '+43', flag: 'AT', regex: /^\d{10,13}$/ },               
  { code: 'PT', name: 'Portugal',       dialCode: '+351',flag: 'PT', regex: /^\d{9}$/ },                   
  { code: 'GR', name: 'Greece',         dialCode: '+30', flag: 'GR', regex: /^\d{10}$/ },                  
  { code: 'IL', name: 'Israel',         dialCode: '+972',flag: 'IL', regex: /^\d{9}$/ },                   
  { code: 'TH', name: 'Thailand',       dialCode: '+66', flag: 'TH', regex: /^\d{9}$/ },                   
  { code: 'MY', name: 'Malaysia',       dialCode: '+60', flag: 'MY', regex: /^\d{9,10}$/ },               
  { code: 'ID', name: 'Indonesia',      dialCode: '+62', flag: 'ID', regex: /^\d{9,12}$/ },                
  { code: 'PH', name: 'Philippines',    dialCode: '+63', flag: 'PH', regex: /^\d{10}$/ },                 
  { code: 'VN', name: 'Vietnam',        dialCode: '+84', flag: 'VN', regex: /^\d{9,10}$/ },                
  { code: 'PK', name: 'Pakistan',       dialCode: '+92', flag: 'PK', regex: /^\d{10}$/ },                 
  { code: 'BD', name: 'Bangladesh',     dialCode: '+880',flag: 'BD', regex: /^\d{10}$/ },              
  { code: 'NZ', name: 'New Zealand',    dialCode: '+64', flag: 'NZ', regex: /^\d{8,10}$/ },                
  { code: 'IE', name: 'Ireland',        dialCode: '+353',flag: 'IE', regex: /^\d{9}$/ },                   
];